window.PRODUCTS = [
  {
    id: "sensai-absolute-silk-micro-mousse-wash",
    name: "Sensai Absolute Silk Micro Mousse Wash",
    brand: "Sensai",
    line: "Absolute Silk",
    category: "Уход за кожей",
    subcategory: "Очищение",
    price: 78,
    badge: "Хит продаж",
    visual: "sensai",
    image: "./assets/sensai-wash.svg",
    volume: "180 мл",
    shades: [],
    tags: ["очищение", "sensai", "new"],
    description: "Нежная очищающая мусс-пенка для утреннего и вечернего ухода, которая помогает оставить кожу мягкой, свежей и визуально более гладкой.",
    howToUse: "Нанесите небольшое количество на влажную кожу, вспеньте мягкими круговыми движениями и тщательно смойте водой.",
    details: [
      "Подходит для витрины с акцентом на премиальный уход",
      "Сильный флагманский SKU для разделов Sensai",
      "Хорошо сочетается с лосьонами и кремами в допродажах",
    ],
    officialUrl: "https://www.sensai-cosmetics.com/",
  },
  {
    id: "sensai-cellular-performance-cream",
    name: "Sensai Cellular Performance Cream",
    brand: "Sensai",
    line: "Cellular Performance",
    category: "Уход за кожей",
    subcategory: "Крем",
    price: 164,
    badge: "Новинка",
    visual: "gold",
    image: "./assets/sensai-cream.svg",
    volume: "40 мл",
    shades: [],
    tags: ["крем", "sensai", "new", "сияние"],
    description: "Насыщенный крем для ежедневного ухода, созданный для ощущения комфорта, гладкости и ухоженного сияния кожи.",
    howToUse: "Используйте утром и вечером после лосьона или эссенции, распределяя крем по лицу и шее.",
    details: [
      "Премиальный крем для высокого среднего чека",
      "Подходит для антивозрастных и сияющих уходовых подборок",
      "Хорошо работает в наборах и подарочных комплектах",
    ],
    officialUrl: "https://www.sensai-cosmetics.com/",
  },
  {
    id: "sensai-lotion-ii-moist",
    name: "Sensai Cellular Performance Lotion II Moist",
    brand: "Sensai",
    line: "Cellular Performance",
    category: "Уход за кожей",
    subcategory: "Лосьон",
    price: 92,
    badge: "Уход",
    visual: "sensai",
    image: "./assets/sensai-wash.svg",
    volume: "125 мл",
    shades: [],
    tags: ["лосьон", "sensai", "увлажнение"],
    description: "Увлажняющий лосьон для подготовки кожи к последующим этапам ухода и более комфортного ощущения после очищения.",
    howToUse: "Нанесите на ладони или ватный диск и мягко распределите по лицу после очищения.",
    details: [
      "Хорошо подходит для набора с кремом",
      "Помогает объяснить покупателю полноценный ритуал ухода",
      "Легко продвигать как ежедневный базовый продукт",
    ],
    officialUrl: "https://www.sensai-cosmetics.com/",
  },
  {
    id: "sensai-total-finish-foundation",
    name: "Sensai Total Finish Foundation",
    brand: "Sensai",
    line: "Make-up",
    category: "Макияж",
    subcategory: "Тональная основа",
    price: 72,
    badge: "Тон",
    visual: "gold",
    image: "./assets/sensai-cream.svg",
    volume: "11 г",
    shades: ["TF 12", "TF 22", "TF 23", "TF 24"],
    tags: ["тон", "sensai", "макияж"],
    description: "Компактная тональная основа с мягким финишем для ровного, ухоженного и естественно сияющего тона кожи.",
    howToUse: "Наберите средство спонжем и распределите от центра лица к контурам, наслаивая покрытие при необходимости.",
    details: [
      "Подходит для цветовой матрицы оттенков",
      "Можно продавать вместе с базой и пудрой",
      "Хорошо расширяет Sensai за пределы ухода",
    ],
    officialUrl: "https://www.sensai-cosmetics.com/",
  },
  {
    id: "dg-the-only-one-matte-lipstick",
    name: "D&G The Only One Matte Lipstick",
    brand: "D&G Beauty",
    line: "The Only One",
    category: "Макияж",
    subcategory: "Помада",
    price: 49,
    badge: "Выбор редакции",
    visual: "dg",
    image: "./assets/dg-lipstick.svg",
    volume: "3.5 г",
    shades: ["Nude", "Rose", "Red", "Berry"],
    tags: ["помада", "dg", "цвет"],
    description: "Насыщенная матовая помада с бархатным финишем для выразительного макияжа губ и яркого fashion-образа.",
    howToUse: "Нанесите от центра губ к контуру. Для более четкого результата используйте карандаш для губ.",
    details: [
      "Удобная входная цена для новых покупателей",
      "Подходит для визуальных рекламных кампаний",
      "Легко добавляется как дополнительный товар в корзину",
    ],
    officialUrl: "https://www.dolcegabbana.com/beauty/",
  },
  {
    id: "dg-devotion-eau-de-parfum",
    name: "D&G Devotion Eau de Parfum",
    brand: "D&G Beauty",
    line: "Devotion",
    category: "Ароматы",
    subcategory: "Парфюмерная вода",
    price: 118,
    badge: "Лимитировано",
    visual: "rose",
    image: "./assets/dg-fragrance.svg",
    volume: "50 мл",
    shades: [],
    tags: ["аромат", "dg", "подарок", "new"],
    description: "Теплый сияющий аромат для подарков, премиальных подборок и образа с выразительным средиземноморским настроением.",
    howToUse: "Распылите на точки пульса: шею, запястья и зону за ушами. Не растирайте после нанесения.",
    details: [
      "Подходит для сезонных подарочных кампаний",
      "Помогает расширить магазин за пределы ухода за кожей",
      "Хороший акцентный товар для межкатегорийной витрины",
    ],
    officialUrl: "https://www.dolcegabbana.com/beauty/",
  },
  {
    id: "dg-everkiss-liquid-lip",
    name: "D&G Everkiss Liquid Lip",
    brand: "D&G Beauty",
    line: "Everkiss",
    category: "Макияж",
    subcategory: "Жидкая помада",
    price: 52,
    badge: "Цвет",
    visual: "dg",
    image: "./assets/dg-lipstick.svg",
    volume: "5 мл",
    shades: ["Soft Nude", "Iconic Red", "Warm Rose", "Deep Plum"],
    tags: ["помада", "dg", "макияж", "new"],
    description: "Жидкая помада с выразительным цветом и современным финишем для стойкого акцента в макияже.",
    howToUse: "Нанесите аппликатором тонким слоем. Дайте средству зафиксироваться несколько секунд.",
    details: [
      "Подходит для фильтра по оттенкам",
      "Хорошо смотрится в подборках макияжа губ",
      "Можно допродавать с ароматами и подарочными наборами",
    ],
    officialUrl: "https://www.dolcegabbana.com/beauty/",
  },
  {
    id: "dg-passioneyes-mascara",
    name: "D&G Passioneyes Mascara",
    brand: "D&G Beauty",
    line: "Passioneyes",
    category: "Макияж",
    subcategory: "Тушь",
    price: 46,
    badge: "Макияж глаз",
    visual: "dg",
    image: "./assets/dg-lipstick.svg",
    volume: "6 мл",
    shades: ["Black"],
    tags: ["тушь", "dg", "макияж глаз"],
    description: "Тушь для выразительного взгляда, которая помогает подчеркнуть ресницы и завершить макияж глаз.",
    howToUse: "Нанесите от корней ресниц к кончикам зигзагообразными движениями. При необходимости добавьте второй слой.",
    details: [
      "Базовый продукт для категории макияжа глаз",
      "Подходит для комплекта с помадой",
      "Нужен в каталоге для полноценной линейки D&G Beauty",
    ],
    officialUrl: "https://www.dolcegabbana.com/beauty/",
  },
];
